// CountryCodeSelect.tsx
import React from "react";
import { Select } from "antd";
import Flag from "react-world-flags";

// List of country codes with ISO 3166-1 alpha-2 codes
const countryCodes = [
  { code: "+93", country: "AF", countryName: "Afghanistan" },
  { code: "+355", country: "AL", countryName: "Albania" },
  { code: "+213", country: "DZ", countryName: "Algeria" },
  { code: "+1-684", country: "AS", countryName: "American Samoa" },
  { code: "+376", country: "AD", countryName: "Andorra" },
  { code: "+244", country: "AO", countryName: "Angola" },
  { code: "+1-264", country: "AI", countryName: "Anguilla" },
  { code: "+672", country: "AQ", countryName: "Antarctica" },
  { code: "+1-268", country: "AG", countryName: "Antigua and Barbuda" },
  { code: "+54", country: "AR", countryName: "Argentina" },
  { code: "+374", country: "AM", countryName: "Armenia" },
  { code: "+297", country: "AW", countryName: "Aruba" },
  { code: "+61", country: "AU", countryName: "Australia" },
  { code: "+43", country: "AT", countryName: "Austria" },
  { code: "+994", country: "AZ", countryName: "Azerbaijan" },
  { code: "+1-242", country: "BS", countryName: "Bahamas" },
  { code: "+973", country: "BH", countryName: "Bahrain" },
  { code: "+880", country: "BD", countryName: "Bangladesh" },
  { code: "+1-246", country: "BB", countryName: "Barbados" },
  { code: "+375", country: "BY", countryName: "Belarus" },
  { code: "+32", country: "BE", countryName: "Belgium" },
  { code: "+501", country: "BZ", countryName: "Belize" },
  { code: "+229", country: "BJ", countryName: "Benin" },
  { code: "+1-441", country: "BM", countryName: "Bermuda" },
  { code: "+975", country: "BT", countryName: "Bhutan" },
  { code: "+591", country: "BO", countryName: "Bolivia" },
  { code: "+387", country: "BA", countryName: "Bosnia and Herzegovina" },
  { code: "+267", country: "BW", countryName: "Botswana" },
  { code: "+55", country: "BR", countryName: "Brazil" },
  {
    code: "+246",
    country: "IO",
    countryName: "British Indian Ocean Territory",
  },
  { code: "+673", country: "BN", countryName: "Brunei" },
  { code: "+359", country: "BG", countryName: "Bulgaria" },
  { code: "+226", country: "BF", countryName: "Burkina Faso" },
  { code: "+257", country: "BI", countryName: "Burundi" },
  { code: "+855", country: "KH", countryName: "Cambodia" },
  { code: "+237", country: "CM", countryName: "Cameroon" },
  { code: "+1", country: "CA", countryName: "Canada" },
  { code: "+238", country: "CV", countryName: "Cape Verde" },
  { code: "+1-345", country: "KY", countryName: "Cayman Islands" },
  { code: "+236", country: "CF", countryName: "Central African Republic" },
  { code: "+235", country: "TD", countryName: "Chad" },
  { code: "+56", country: "CL", countryName: "Chile" },
  { code: "+86", country: "CN", countryName: "China" },
  { code: "+61", country: "CX", countryName: "Christmas Island" },
  { code: "+61", country: "CC", countryName: "Cocos (Keeling) Islands" },
  { code: "+57", country: "CO", countryName: "Colombia" },
  { code: "+269", country: "KM", countryName: "Comoros" },
  { code: "+242", country: "CG", countryName: "Congo" },
  { code: "+243", country: "CD", countryName: "Congo (DRC)" },
  { code: "+682", country: "CK", countryName: "Cook Islands" },
  { code: "+506", country: "CR", countryName: "Costa Rica" },
  { code: "+225", country: "CI", countryName: "Côte d'Ivoire" },
  { code: "+385", country: "HR", countryName: "Croatia" },
  { code: "+53", country: "CU", countryName: "Cuba" },
  { code: "+357", country: "CY", countryName: "Cyprus" },
  { code: "+420", country: "CZ", countryName: "Czech Republic" },
  { code: "+45", country: "DK", countryName: "Denmark" },
  { code: "+253", country: "DJ", countryName: "Djibouti" },
  { code: "+1-767", country: "DM", countryName: "Dominica" },
  { code: "+1-809", country: "DO", countryName: "Dominican Republic" },
  { code: "+593", country: "EC", countryName: "Ecuador" },
  { code: "+20", country: "EG", countryName: "Egypt" },
  { code: "+503", country: "SV", countryName: "El Salvador" },
  { code: "+240", country: "GQ", countryName: "Equatorial Guinea" },
  { code: "+291", country: "ER", countryName: "Eritrea" },
  { code: "+372", country: "EE", countryName: "Estonia" },
  { code: "+251", country: "ET", countryName: "Ethiopia" },
  { code: "+500", country: "FK", countryName: "Falkland Islands" },
  { code: "+298", country: "FO", countryName: "Faroe Islands" },
  { code: "+679", country: "FJ", countryName: "Fiji" },
  { code: "+358", country: "FI", countryName: "Finland" },
  { code: "+33", country: "FR", countryName: "France" },
  { code: "+594", country: "GF", countryName: "French Guiana" },
  { code: "+689", country: "PF", countryName: "French Polynesia" },
  { code: "+241", country: "GA", countryName: "Gabon" },
  { code: "+220", country: "GM", countryName: "Gambia" },
  { code: "+995", country: "GE", countryName: "Georgia" },
  { code: "+49", country: "DE", countryName: "Germany" },
  { code: "+233", country: "GH", countryName: "Ghana" },
  { code: "+350", country: "GI", countryName: "Gibraltar" },
  { code: "+30", country: "GR", countryName: "Greece" },
  { code: "+299", country: "GL", countryName: "Greenland" },
  { code: "+1-473", country: "GD", countryName: "Grenada" },
  { code: "+590", country: "GP", countryName: "Guadeloupe" },
  { code: "+1-671", country: "GU", countryName: "Guam" },
  { code: "+502", country: "GT", countryName: "Guatemala" },
  { code: "+224", country: "GN", countryName: "Guinea" },
  { code: "+245", country: "GW", countryName: "Guinea-Bissau" },
  { code: "+592", country: "GY", countryName: "Guyana" },
  { code: "+509", country: "HT", countryName: "Haiti" },
  { code: "+504", country: "HN", countryName: "Honduras" },
  { code: "+852", country: "HK", countryName: "Hong Kong" },
  { code: "+36", country: "HU", countryName: "Hungary" },
  { code: "+354", country: "IS", countryName: "Iceland" },
  { code: "+91", country: "IN", countryName: "India" },
  { code: "+62", country: "ID", countryName: "Indonesia" },
  { code: "+98", country: "IR", countryName: "Iran" },
  { code: "+964", country: "IQ", countryName: "Iraq" },
  { code: "+353", country: "IE", countryName: "Ireland" },
  { code: "+972", country: "IL", countryName: "Israel" },
  { code: "+39", country: "IT", countryName: "Italy" },
  { code: "+1-876", country: "JM", countryName: "Jamaica" },
  { code: "+81", country: "JP", countryName: "Japan" },
  { code: "+962", country: "JO", countryName: "Jordan" },
  { code: "+7", country: "KZ", countryName: "Kazakhstan" },
  { code: "+254", country: "KE", countryName: "Kenya" },
  { code: "+686", country: "KI", countryName: "Kiribati" },
  { code: "+383", country: "XK", countryName: "Kosovo" },
  { code: "+965", country: "KW", countryName: "Kuwait" },
  { code: "+996", country: "KG", countryName: "Kyrgyzstan" },
  { code: "+856", country: "LA", countryName: "Laos" },
  { code: "+371", country: "LV", countryName: "Latvia" },
  { code: "+961", country: "LB", countryName: "Lebanon" },
  { code: "+266", country: "LS", countryName: "Lesotho" },
  { code: "+231", country: "LR", countryName: "Liberia" },
  { code: "+218", country: "LY", countryName: "Libya" },
  { code: "+423", country: "LI", countryName: "Liechtenstein" },
  { code: "+370", country: "LT", countryName: "Lithuania" },
  { code: "+352", country: "LU", countryName: "Luxembourg" },
  { code: "+853", country: "MO", countryName: "Macau" },
  { code: "+389", country: "MK", countryName: "North Macedonia" },
  { code: "+261", country: "MG", countryName: "Madagascar" },
  { code: "+265", country: "MW", countryName: "Malawi" },
  { code: "+60", country: "MY", countryName: "Malaysia" },
  { code: "+960", country: "MV", countryName: "Maldives" },
  { code: "+223", country: "ML", countryName: "Mali" },
  { code: "+356", country: "MT", countryName: "Malta" },
  { code: "+692", country: "MH", countryName: "Marshall Islands" },
  { code: "+596", country: "MQ", countryName: "Martinique" },
  { code: "+222", country: "MR", countryName: "Mauritania" },
  { code: "+230", country: "MU", countryName: "Mauritius" },
  { code: "+262", country: "YT", countryName: "Mayotte" },
  { code: "+52", country: "MX", countryName: "Mexico" },
  { code: "+691", country: "FM", countryName: "Micronesia" },
  { code: "+373", country: "MD", countryName: "Moldova" },
  { code: "+377", country: "MC", countryName: "Monaco" },
  { code: "+976", country: "MN", countryName: "Mongolia" },
  { code: "+382", country: "ME", countryName: "Montenegro" },
  { code: "+1-664", country: "MS", countryName: "Montserrat" },
  { code: "+212", country: "MA", countryName: "Morocco" },
  { code: "+258", country: "MZ", countryName: "Mozambique" },
  { code: "+95", country: "MM", countryName: "Myanmar" },
  { code: "+264", country: "NA", countryName: "Namibia" },
  { code: "+674", country: "NR", countryName: "Nauru" },
  { code: "+977", country: "NP", countryName: "Nepal" },
  { code: "+31", country: "NL", countryName: "Netherlands" },
  { code: "+687", country: "NC", countryName: "New Caledonia" },
  { code: "+64", country: "NZ", countryName: "New Zealand" },
  { code: "+505", country: "NI", countryName: "Nicaragua" },
  { code: "+227", country: "NE", countryName: "Niger" },
  { code: "+234", country: "NG", countryName: "Nigeria" },
  { code: "+683", country: "NU", countryName: "Niue" },
  { code: "+672", country: "NF", countryName: "Norfolk Island" },
  { code: "+850", country: "KP", countryName: "North Korea" },
  { code: "+1-670", country: "MP", countryName: "Northern Mariana Islands" },
  { code: "+47", country: "NO", countryName: "Norway" },
  { code: "+968", country: "OM", countryName: "Oman" },
  { code: "+92", country: "PK", countryName: "Pakistan" },
  { code: "+680", country: "PW", countryName: "Palau" },
  { code: "+970", country: "PS", countryName: "Palestine" },
  { code: "+507", country: "PA", countryName: "Panama" },
  { code: "+675", country: "PG", countryName: "Papua New Guinea" },
  { code: "+595", country: "PY", countryName: "Paraguay" },
  { code: "+51", country: "PE", countryName: "Peru" },
  { code: "+63", country: "PH", countryName: "Philippines" },
  { code: "+48", country: "PL", countryName: "Poland" },
  { code: "+351", country: "PT", countryName: "Portugal" },
  { code: "+1-787", country: "PR", countryName: "Puerto Rico" },
  { code: "+974", country: "QA", countryName: "Qatar" },
  { code: "+262", country: "RE", countryName: "Réunion" },
  { code: "+40", country: "RO", countryName: "Romania" },
  { code: "+7", country: "RU", countryName: "Russia" },
  { code: "+250", country: "RW", countryName: "Rwanda" },
  { code: "+685", country: "WS", countryName: "Samoa" },
  { code: "+378", country: "SM", countryName: "San Marino" },
  { code: "+239", country: "ST", countryName: "São Tomé and Príncipe" },
  { code: "+966", country: "SA", countryName: "Saudi Arabia" },
  { code: "+221", country: "SN", countryName: "Senegal" },
  { code: "+381", country: "RS", countryName: "Serbia" },
  { code: "+248", country: "SC", countryName: "Seychelles" },
  { code: "+232", country: "SL", countryName: "Sierra Leone" },
  { code: "+65", country: "SG", countryName: "Singapore" },
  { code: "+421", country: "SK", countryName: "Slovakia" },
  { code: "+386", country: "SI", countryName: "Slovenia" },
  { code: "+677", country: "SB", countryName: "Solomon Islands" },
  { code: "+252", country: "SO", countryName: "Somalia" },
  { code: "+27", country: "ZA", countryName: "South Africa" },
  { code: "+82", country: "KR", countryName: "South Korea" },
  { code: "+211", country: "SS", countryName: "South Sudan" },
  { code: "+34", country: "ES", countryName: "Spain" },
  { code: "+94", country: "LK", countryName: "Sri Lanka" },
  { code: "+249", country: "SD", countryName: "Sudan" },
  { code: "+597", country: "SR", countryName: "Suriname" },
  { code: "+268", country: "SZ", countryName: "Eswatini" },
  { code: "+46", country: "SE", countryName: "Sweden" },
  { code: "+41", country: "CH", countryName: "Switzerland" },
  { code: "+963", country: "SY", countryName: "Syria" },
  { code: "+886", country: "TW", countryName: "Taiwan" },
  { code: "+992", country: "TJ", countryName: "Tajikistan" },
  { code: "+255", country: "TZ", countryName: "Tanzania" },
  { code: "+66", country: "TH", countryName: "Thailand" },
  { code: "+228", country: "TG", countryName: "Togo" },
  { code: "+690", country: "TK", countryName: "Tokelau" },
  { code: "+676", country: "TO", countryName: "Tonga" },
  { code: "+1-868", country: "TT", countryName: "Trinidad and Tobago" },
  { code: "+216", country: "TN", countryName: "Tunisia" },
  { code: "+90", country: "TR", countryName: "Turkey" },
  { code: "+993", country: "TM", countryName: "Turkmenistan" },
  { code: "+688", country: "TV", countryName: "Tuvalu" },
  { code: "+1-340", country: "VI", countryName: "U.S. Virgin Islands" },
  { code: "+256", country: "UG", countryName: "Uganda" },
  { code: "+380", country: "UA", countryName: "Ukraine" },
  { code: "+971", country: "AE", countryName: "United Arab Emirates" },
  { code: "+44", country: "GB", countryName: "United Kingdom" },
  { code: "+1", country: "US", countryName: "United States" },
  { code: "+598", country: "UY", countryName: "Uruguay" },
  { code: "+998", country: "UZ", countryName: "Uzbekistan" },
  { code: "+678", country: "VU", countryName: "Vanuatu" },
  { code: "+379", country: "VA", countryName: "Vatican City" },
  { code: "+58", country: "VE", countryName: "Venezuela" },
  { code: "+84", country: "VN", countryName: "Vietnam" },
  { code: "+681", country: "WF", countryName: "Wallis and Futuna" },
  { code: "+967", country: "YE", countryName: "Yemen" },
  { code: "+260", country: "ZM", countryName: "Zambia" },
  { code: "+263", country: "ZW", countryName: "Zimbabwe" },
];

const { Option } = Select;

interface CountryCodeSelectProps {
  value: string;
  onChange: (value: string) => void;
}

const CountryCodeSelect: React.FC<CountryCodeSelectProps> = ({
  value,
  onChange,
}) => {
  return (
    <Select
      showSearch
      value={value}
      onChange={onChange}
      style={{ width: "30%" }} // Adjust width to accommodate flags
      optionLabelProp="label"
      filterOption={
        (input, option) =>
          (option?.label as string)
            .toLowerCase()
            .includes(input.toLowerCase()) ||
          (option?.value as string).toLowerCase().includes(input.toLowerCase()) // Compare with the value if necessary
      }
      placeholder="Select Country Code"
    >
      {countryCodes.map((country) => (
        <Option
          key={country.code}
          value={country.code}
          label={`${country.countryName} ${country.code}`} // Label contains both country name and code
          style={{
            display: "flex",
            alignItems: "center",
          }}
        >
          <Flag
            code={country.country}
            style={{ width: "24px", height: "16px", marginRight: "8px" }}
          />
          <span>{`${country.countryName} (${country.code})`}</span>
        </Option>
      ))}
    </Select>
  );
};

export default CountryCodeSelect;
